version: "3.9"

volumes: 
  todo-db:

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - todo-db:/var/lib/postgresql/data
  
  back:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"


  front:
    build:
      context: frontend
      dockerfile: Dockerfile

    ports: 
      - "8080:8080"